# Generated by Django 2.0.7 on 2018-08-02 15:35

from django.db import migrations
import django_2gis_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='address',
            field=django_2gis_maps.fields.AddressField(max_length=255),
        ),
    ]
