# Generated by Django 2.0.7 on 2018-08-02 15:50

from django.db import migrations
import django_2gis_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20180802_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='geolocation',
            field=django_2gis_maps.fields.GeoLocationField(blank=True),
        ),
    ]
